from __future__ import annotations

import re
import shutil
from html import escape
from pathlib import Path
from typing import Dict, List, Optional

from config import HTML_SKILL_DIR, OUTPUTS_DIR, TEMPLATE_THEME_MAP
from models import ParsedFigure, ParsedTable, SlideContent


def _copy_assets(output_dir: Path) -> None:
    src_assets = HTML_SKILL_DIR / "assets"
    dst_assets = output_dir / "assets"
    if dst_assets.exists():
        shutil.rmtree(dst_assets)
    shutil.copytree(src_assets, dst_assets)


def _footer(idx: int, total: int) -> str:
    return (
        f'<div class="deck-footer"><span class="dim2">Paper2PPT</span>'
        f'<span class="slide-number" data-current="{idx}" data-total="{total}"></span></div>'
    )


def _split_columns(items: List[str], count: int) -> List[List[str]]:
    cols = [[] for _ in range(count)]
    for idx, item in enumerate(items):
        cols[idx % count].append(item)
    return cols


def _is_english(language: str) -> bool:
    return (language or "").lower().startswith("en")


def _label(language: str, zh: str, en: str) -> str:
    return en if _is_english(language) else zh


def _rich_text(text: str) -> str:
    """Render safe inline Markdown/LaTeX-ish text for slide body copy."""
    safe = escape(text or "")
    safe = re.sub(
        r"\$\$(.+?)\$\$",
        r"<span class='math math-block'>\1</span>",
        safe,
        flags=re.DOTALL,
    )
    safe = re.sub(r"\\\[(.+?)\\\]", r"<span class='math math-block'>\1</span>", safe, flags=re.DOTALL)
    safe = re.sub(r"\$(.+?)\$", r"<span class='math'>\1</span>", safe)
    safe = re.sub(r"\\\((.+?)\\\)", r"<span class='math'>\1</span>", safe)
    safe = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", safe)
    return safe.replace("\n", "<br>")


def _title_text(text: str) -> str:
    return _rich_text(text)


def _bullet_cards(items: List[str]) -> str:
    return "".join(
        f"<li class='card card-accent'><p>{_rich_text(item)}</p></li>"
        for item in items
    )


def _figure_src(figure: Optional[ParsedFigure]) -> str:
    if not figure or not figure.image_path:
        return ""
    return f"figures/{Path(figure.image_path).name}"


def _figure_block(figure: Optional[ParsedFigure], accent: str, min_height: int = 260) -> str:
    if figure and figure.image_path and Path(figure.image_path).exists():
        src = _figure_src(figure)
        raw_alt = figure.caption or figure.figure_id
        if raw_alt.lower().startswith("user uploaded figure"):
            raw_alt = "Figure"
        alt = escape(raw_alt)
        return (
            f"<div class='card' style='height:{min_height}px;overflow:hidden;display:flex;align-items:center;justify-content:center;padding:10px'>"
            f"<img src='{src}' alt='{alt}' style='width:100%;height:100%;object-fit:contain;border-radius:16px'/>"
            f"</div>"
        )
    return (
        f"<div class='card' style='min-height:{min_height}px;display:flex;align-items:center;justify-content:center;"
        f"background:linear-gradient(135deg,{accent}22,#fff)'><p>Image not available</p></div>"
    )


def _render_cover(slide: SlideContent, idx: int, total: int, language: str) -> str:
    subtitle = _rich_text(slide.bullets[0]) if slide.bullets else _label(language, "Paper2PPT 自动生成的学术汇报", "Academic presentation generated by Paper2PPT")
    notes = _rich_text(slide.notes or "")
    kicker = _label(language, "Paper2PPT · 学术汇报", "Paper2PPT · Academic Presentation")
    return f"""
  <section class="slide" data-title="{escape(slide.title)}">
    <p class="kicker">{kicker}</p>
    <h1 class="h1 anim-fade-up" data-anim="fade-up">{_title_text(slide.title)}</h1>
    <p class="lead mt-m">{subtitle}</p>
    <div class="mt-l grid g2">
      {''.join(f"<div class='card'><p>{_rich_text(item)}</p></div>" for item in slide.bullets[1:3])}
    </div>
    {_footer(idx, total)}
    <div class="notes">{notes}</div>
  </section>"""


def _render_bullets(slide: SlideContent, idx: int, total: int, accent: str) -> str:
    notes = _rich_text(slide.notes or "")
    return f"""
  <section class="slide" data-title="{escape(slide.title)}">
    <p class="kicker" style="color:{accent}">Section</p>
    <h2 class="h2">{_title_text(slide.title)}</h2>
    <ul class="grid g1 anim-stagger-list" style="list-style:none;padding:0;margin:0;gap:14px" data-anim-target>
      {_bullet_cards(slide.bullets)}
    </ul>
    {_footer(idx, total)}
    <div class="notes">{notes}</div>
  </section>"""


def _render_columns(slide: SlideContent, idx: int, total: int, accent: str, col_count: int) -> str:
    notes = _rich_text(slide.notes or "")
    columns = _split_columns(slide.bullets, col_count)
    grid_class = "g2" if col_count == 2 else "g3"
    cols_html = ""
    for col in columns:
        items = "".join(f"<li><p>{_rich_text(item)}</p></li>" for item in col)
        cols_html += f"<div class='card'><ul style='margin:0;padding-left:18px'>{items}</ul></div>"
    return f"""
  <section class="slide" data-title="{escape(slide.title)}">
    <p class="kicker" style="color:{accent}">Structured View</p>
    <h2 class="h2">{_title_text(slide.title)}</h2>
    <div class="grid {grid_class} mt-m">{cols_html}</div>
    {_footer(idx, total)}
    <div class="notes">{notes}</div>
  </section>"""


def _table_src(table: Optional[ParsedTable]) -> str:
    if not table or not table.image_path:
        return ""
    return f"tables/{Path(table.image_path).name}"


def _table_block(table: Optional[ParsedTable], accent: str, min_height: int = 320) -> str:
    if table and table.image_path and Path(table.image_path).exists():
        src = _table_src(table)
        alt = escape(table.table_id)
        return (
            f"<div class='card' style='min-height:{min_height}px;display:flex;align-items:center;justify-content:center;padding:12px'>"
            f"<img src='{src}' alt='{alt}' style='max-width:100%;max-height:{min_height + 80}px;border-radius:12px'/>"
            f"</div>"
        )
    return (
        f"<div class='card' style='min-height:{min_height}px;display:flex;align-items:center;justify-content:center;"
        f"background:linear-gradient(135deg,{accent}16,#fff)'><p>Table screenshot not available</p></div>"
    )


def _render_table(slide: SlideContent, idx: int, total: int, accent: str, table: Optional[ParsedTable] = None) -> str:
    notes = _rich_text(slide.notes or "")
    if table and table.image_path:
        side_cards = "".join(f"<div class='card'><p>{_rich_text(item)}</p></div>" for item in slide.bullets[:3])
        return f"""
  <section class="slide" data-title="{escape(slide.title)}">
    <p class="kicker" style="color:{accent}">Table Screenshot</p>
    <h2 class="h2">{_title_text(slide.title)}</h2>
    <div class="grid g2 mt-m">
      {_table_block(table, accent, 320)}
      <div class="grid g1">{side_cards}</div>
    </div>
    {_footer(idx, total)}
    <div class="notes">{notes}</div>
  </section>"""
    rows = "".join(
        f"<tr><td style='padding:10px;border-bottom:1px solid rgba(148,163,184,.22)'>{_rich_text(item)}</td></tr>"
        for item in slide.bullets
    )
    return f"""
  <section class="slide" data-title="{escape(slide.title)}">
    <p class="kicker" style="color:{accent}">Tabular Summary</p>
    <h2 class="h2">{_title_text(slide.title)}</h2>
    <div class="card mt-m">
      <table style="width:100%;border-collapse:collapse;font-size:18px">
        {rows}
      </table>
    </div>
    {_footer(idx, total)}
    <div class="notes">{notes}</div>
  </section>"""


def _render_big_quote(slide: SlideContent, idx: int, total: int) -> str:
    quote = _rich_text(slide.bullets[0]) if slide.bullets else _title_text(slide.title)
    note = _rich_text(slide.bullets[1]) if len(slide.bullets) > 1 else ""
    notes = _rich_text(slide.notes or "")
    return f"""
  <section class="slide" data-title="{escape(slide.title)}">
    <p class="kicker">Key Message</p>
    <blockquote class="card mt-l" style="font-size:32px;line-height:1.5;padding:32px">
      “{quote}”
    </blockquote>
    <p class="lead mt-m">{note}</p>
    {_footer(idx, total)}
    <div class="notes">{notes}</div>
  </section>"""


def _render_metric_grid(slide: SlideContent, idx: int, total: int, accent: str) -> str:
    notes = _rich_text(slide.notes or "")
    cards = "".join(
        f"<div class='card'><h3 style='color:{accent};font-size:28px;margin:0 0 8px'>{_rich_text(item.split(':', 1)[0])}</h3><p>{_rich_text(item)}</p></div>"
        for item in slide.bullets[:6]
    )
    return f"""
  <section class="slide" data-title="{escape(slide.title)}">
    <p class="kicker" style="color:{accent}">Metrics</p>
    <h2 class="h2">{_title_text(slide.title)}</h2>
    <div class="grid g3 mt-m">{cards}</div>
    {_footer(idx, total)}
    <div class="notes">{notes}</div>
  </section>"""


def _render_visual_grid(slide: SlideContent, idx: int, total: int, accent: str, hero: bool = False) -> str:
    notes = _rich_text(slide.notes or "")
    if hero:
        lead = _rich_text(slide.bullets[0]) if slide.bullets else ""
        side_cards = "".join(f"<div class='card'><p>{_rich_text(item)}</p></div>" for item in slide.bullets[1:4])
        return f"""
  <section class="slide" data-title="{escape(slide.title)}">
    <p class="kicker" style="color:{accent}">Visual Story</p>
    <h2 class="h2">{_title_text(slide.title)}</h2>
    <div class="grid g2 mt-m">
      <div class="card" style="min-height:260px;display:flex;align-items:center;justify-content:center;background:linear-gradient(135deg,{accent}22,#fff)">
        <p style="font-size:28px;line-height:1.5">{lead}</p>
      </div>
      <div class="grid g1">{side_cards}</div>
    </div>
    {_footer(idx, total)}
    <div class="notes">{notes}</div>
  </section>"""
    cards = "".join(
        f"<div class='card' style='min-height:120px;display:flex;align-items:center;justify-content:center;background:linear-gradient(135deg,{accent}14,#fff)'><p>{_rich_text(item)}</p></div>"
        for item in slide.bullets[:6]
    )
    return f"""
  <section class="slide" data-title="{escape(slide.title)}">
    <p class="kicker" style="color:{accent}">Visual Grid</p>
    <h2 class="h2">{_title_text(slide.title)}</h2>
    <div class="grid g3 mt-m">{cards}</div>
    {_footer(idx, total)}
    <div class="notes">{notes}</div>
  </section>"""


def _render_statement(slide: SlideContent, idx: int, total: int, accent: str) -> str:
    notes = _rich_text(slide.notes or "")
    statement = _rich_text(slide.bullets[0]) if slide.bullets else _title_text(slide.title)
    supports = "".join(
        f"<div class='card'><p>{_rich_text(item)}</p></div>"
        for item in slide.bullets[1:4]
    )
    return f"""
  <section class="slide" data-title="{escape(slide.title)}">
    <p class="kicker" style="color:{accent}">Core Statement</p>
    <h2 class="h2">{_title_text(slide.title)}</h2>
    <div class="card mt-m" style="padding:34px;background:linear-gradient(135deg,{accent}1f,#fff)">
      <p style="font-size:34px;line-height:1.45;font-weight:760;margin:0">{statement}</p>
    </div>
    <div class="grid g3 mt-m">{supports}</div>
    {_footer(idx, total)}
    <div class="notes">{notes}</div>
  </section>"""


def _render_evidence_cards(slide: SlideContent, idx: int, total: int, accent: str) -> str:
    notes = _rich_text(slide.notes or "")
    labels = ["Claim", "Evidence", "Interpretation", "Caveat"]
    cards = ""
    for item_idx, item in enumerate(slide.bullets[:4]):
        label = labels[item_idx] if item_idx < len(labels) else "Point"
        cards += (
            f"<div class='card' style='min-height:132px'>"
            f"<p class='kicker' style='color:{accent};margin-bottom:8px'>{label}</p>"
            f"<p>{_rich_text(item)}</p></div>"
        )
    return f"""
  <section class="slide" data-title="{escape(slide.title)}">
    <p class="kicker" style="color:{accent}">Evidence Stack</p>
    <h2 class="h2">{_title_text(slide.title)}</h2>
    <div class="grid g2 mt-m">{cards}</div>
    {_footer(idx, total)}
    <div class="notes">{notes}</div>
  </section>"""


def _render_question_matrix(slide: SlideContent, idx: int, total: int, accent: str, language: str) -> str:
    notes = _rich_text(slide.notes or "")
    clue = _label(language, "证据 / 方法 / 结果", "Evidence / Method / Result")
    no_label = _label(language, "编号", "No.")
    question_label = _label(language, "问题拆解", "Question")
    clue_label = _label(language, "验证线索", "Validation Clue")
    rows = ""
    for item_idx, item in enumerate(slide.bullets[:4]):
        rows += f"""
        <tr>
          <td style="width:86px;padding:14px;border-bottom:1px solid rgba(148,163,184,.22);font-weight:800;color:{accent}">RQ{item_idx + 1}</td>
          <td style="padding:14px;border-bottom:1px solid rgba(148,163,184,.22)">{_rich_text(item)}</td>
          <td style="padding:14px;border-bottom:1px solid rgba(148,163,184,.22);color:var(--text-2)">{clue}</td>
        </tr>"""
    return f"""
  <section class="slide" data-title="{escape(slide.title)}">
    <p class="kicker" style="color:{accent}">Research Questions</p>
    <h2 class="h2">{_title_text(slide.title)}</h2>
    <div class="card mt-m" style="padding:0;overflow:hidden">
      <table style="width:100%;border-collapse:collapse;font-size:17px">
        <thead>
          <tr style="background:{accent}12">
            <th style="text-align:left;padding:14px">{no_label}</th>
            <th style="text-align:left;padding:14px">{question_label}</th>
            <th style="text-align:left;padding:14px">{clue_label}</th>
          </tr>
        </thead>
        <tbody>{rows}</tbody>
      </table>
    </div>
    {_footer(idx, total)}
    <div class="notes">{notes}</div>
  </section>"""


def _render_method_swimlane(slide: SlideContent, idx: int, total: int, accent: str, language: str) -> str:
    notes = _rich_text(slide.notes or "")
    stages = (
        ["Input", "Processing", "Core Method", "Validation", "Interpretation"]
        if _is_english(language)
        else ["输入", "处理", "核心方法", "验证", "解释"]
    )
    items = slide.bullets[:5] or [slide.title]
    lanes = ""
    for item_idx, stage in enumerate(stages):
        item = _rich_text(items[item_idx % len(items)])
        lanes += (
            f"<div class='card' style='position:relative;min-height:116px'>"
            f"<p class='kicker' style='color:{accent};margin-bottom:8px'>{stage}</p>"
            f"<p>{item}</p></div>"
        )
    return f"""
  <section class="slide" data-title="{escape(slide.title)}">
    <p class="kicker" style="color:{accent}">Method Flow</p>
    <h2 class="h2">{_title_text(slide.title)}</h2>
    <div class="grid g5 mt-m" style="display:grid;grid-template-columns:repeat(5,1fr);gap:10px">{lanes}</div>
    <div class="mt-m" style="height:8px;border-radius:999px;background:linear-gradient(90deg,{accent},rgba(148,163,184,.35))"></div>
    {_footer(idx, total)}
    <div class="notes">{notes}</div>
  </section>"""


def _render_critique_panel(slide: SlideContent, idx: int, total: int, accent: str, language: str) -> str:
    notes = _rich_text(slide.notes or "")
    left_items = "".join(f"<li><p>{_rich_text(item)}</p></li>" for item in slide.bullets[:3])
    right_items = "".join(f"<li><p>{_rich_text(item)}</p></li>" for item in slide.bullets[3:6])
    if not right_items:
        right_items = f"<li><p>{_label(language, '建议在汇报中准备补充证据或解释边界。', 'Prepare supporting evidence or boundary explanations for the presentation.')}</p></li>"
    left_title = _label(language, "可能被追问", "Likely Questions")
    right_title = _label(language, "应对思路", "Response Strategy")
    return f"""
  <section class="slide" data-title="{escape(slide.title)}">
    <p class="kicker" style="color:{accent}">Reviewer Lens</p>
    <h2 class="h2">{_title_text(slide.title)}</h2>
    <div class="grid g2 mt-m">
      <div class="card" style="border-color:{accent}55">
        <h3 style="margin:0 0 12px;color:{accent}">{left_title}</h3>
        <ul style="margin:0;padding-left:18px">{left_items}</ul>
      </div>
      <div class="card">
        <h3 style="margin:0 0 12px">{right_title}</h3>
        <ul style="margin:0;padding-left:18px">{right_items}</ul>
      </div>
    </div>
    {_footer(idx, total)}
    <div class="notes">{notes}</div>
  </section>"""


def _render_image_side(slide: SlideContent, idx: int, total: int, accent: str, figure: Optional[ParsedFigure], image_left: bool) -> str:
    notes = _rich_text(slide.notes or "")
    items = "".join(f"<li><p>{_rich_text(item)}</p></li>" for item in slide.bullets[:4])
    image = _figure_block(figure, accent, 300)
    text = f"<div class='card'><ul style='margin:0;padding-left:18px'>{items}</ul></div>"
    first, second = (image, text) if image_left else (text, image)
    return f"""
  <section class="slide" data-title="{escape(slide.title)}">
    <p class="kicker" style="color:{accent}">Image + Text</p>
    <h2 class="h2">{_title_text(slide.title)}</h2>
    <div class="grid g2 mt-m">{first}{second}</div>
    {_footer(idx, total)}
    <div class="notes">{notes}</div>
  </section>"""


def _render_figure_hero(slide: SlideContent, idx: int, total: int, accent: str, figure: Optional[ParsedFigure]) -> str:
    notes = _rich_text(slide.notes or "")
    lead = _rich_text(slide.bullets[0]) if slide.bullets else ""
    side_cards = "".join(f"<div class='card'><p>{_rich_text(item)}</p></div>" for item in slide.bullets[1:4])
    return f"""
  <section class="slide" data-title="{escape(slide.title)}">
    <p class="kicker" style="color:{accent}">Figure Insight</p>
    <h2 class="h2">{_title_text(slide.title)}</h2>
    <div class="grid g2 mt-m">
      {_figure_block(figure, accent, 280)}
      <div class="grid g1">
        <div class="card"><p>{lead}</p></div>
        {side_cards}
      </div>
    </div>
    {_footer(idx, total)}
    <div class="notes">{notes}</div>
  </section>"""


def _render_figure_method(slide: SlideContent, idx: int, total: int, accent: str, figure: Optional[ParsedFigure]) -> str:
    notes = _rich_text(slide.notes or "")
    steps = "".join(f"<li><p>{_rich_text(item)}</p></li>" for item in slide.bullets[:4])
    return f"""
  <section class="slide" data-title="{escape(slide.title)}">
    <p class="kicker" style="color:{accent}">Method Figure</p>
    <h2 class="h2">{_title_text(slide.title)}</h2>
    <div class="grid g2 mt-m">
      {_figure_block(figure, accent, 300)}
      <div class="card">
        <ul style="margin:0;padding-left:18px">{steps}</ul>
      </div>
    </div>
    {_footer(idx, total)}
    <div class="notes">{notes}</div>
  </section>"""


def _render_figure_results(slide: SlideContent, idx: int, total: int, accent: str, figure: Optional[ParsedFigure]) -> str:
    notes = _rich_text(slide.notes or "")
    highlights = "".join(
        f"<div class='card'><h4 style='color:{accent};margin:0 0 6px'>Result</h4><p>{_rich_text(item)}</p></div>"
        for item in slide.bullets[:3]
    )
    return f"""
  <section class="slide" data-title="{escape(slide.title)}">
    <p class="kicker" style="color:{accent}">Results Figure</p>
    <h2 class="h2">{_title_text(slide.title)}</h2>
    <div class="grid g2 mt-m">
      {_figure_block(figure, accent, 300)}
      <div class="grid g1">{highlights}</div>
    </div>
    {_footer(idx, total)}
    <div class="notes">{notes}</div>
  </section>"""


def _render_figure_compare(slide: SlideContent, idx: int, total: int, accent: str, figure: Optional[ParsedFigure]) -> str:
    notes = _rich_text(slide.notes or "")
    points = _split_columns(slide.bullets[:6], 2)
    left = "".join(f"<li><p>{_rich_text(item)}</p></li>" for item in points[0])
    right = "".join(f"<li><p>{_rich_text(item)}</p></li>" for item in points[1])
    return f"""
  <section class="slide" data-title="{escape(slide.title)}">
    <p class="kicker" style="color:{accent}">Comparison Figure</p>
    <h2 class="h2">{_title_text(slide.title)}</h2>
    <div class="grid g2 mt-m">
      {_figure_block(figure, accent, 260)}
      <div class="grid g2">
        <div class="card"><ul style="margin:0;padding-left:18px">{left}</ul></div>
        <div class="card"><ul style="margin:0;padding-left:18px">{right}</ul></div>
      </div>
    </div>
    {_footer(idx, total)}
    <div class="notes">{notes}</div>
  </section>"""


def _render_section_divider(slide: SlideContent, idx: int, total: int, accent: str) -> str:
    summary = _rich_text(slide.bullets[0]) if slide.bullets else ""
    notes = _rich_text(slide.notes or "")
    return f"""
  <section class="slide" data-title="{escape(slide.title)}">
    <div class="card" style="min-height:340px;display:flex;flex-direction:column;justify-content:center;background:linear-gradient(135deg,{accent}22,#fff)">
      <p class="kicker" style="color:{accent}">Section Divider</p>
      <h1 class="h1">{_title_text(slide.title)}</h1>
      <p class="lead mt-m">{summary}</p>
    </div>
    {_footer(idx, total)}
    <div class="notes">{notes}</div>
  </section>"""


def _render_checklist(slide: SlideContent, idx: int, total: int, accent: str) -> str:
    notes = _rich_text(slide.notes or "")
    items = "".join(
        f"<li class='card' style='display:flex;align-items:flex-start;gap:10px'><span style='color:{accent};font-weight:700'>✓</span><p>{_rich_text(item)}</p></li>"
        for item in slide.bullets
    )
    return f"""
  <section class="slide" data-title="{escape(slide.title)}">
    <p class="kicker" style="color:{accent}">Checklist</p>
    <h2 class="h2">{_title_text(slide.title)}</h2>
    <ul class="grid g1 mt-m" style="list-style:none;padding:0;margin:0;gap:12px">{items}</ul>
    {_footer(idx, total)}
    <div class="notes">{notes}</div>
  </section>"""


def _render_code(slide: SlideContent, idx: int, total: int, accent: str) -> str:
    notes = _rich_text(slide.notes or "")
    code_body = "\n".join(f"- {item}" for item in slide.bullets)
    return f"""
  <section class="slide" data-title="{escape(slide.title)}">
    <p class="kicker" style="color:{accent}">Technical Detail</p>
    <h2 class="h2">{_title_text(slide.title)}</h2>
    <div class="card mt-m">
      <pre style="margin:0;white-space:pre-wrap;font-size:17px;line-height:1.6">{escape(code_body)}</pre>
    </div>
    {_footer(idx, total)}
    <div class="notes">{notes}</div>
  </section>"""


def _render_thanks(slide: SlideContent, idx: int, total: int, language: str) -> str:
    takeaway = _rich_text(slide.bullets[0]) if slide.bullets else _label(language, "谢谢", "Thanks")
    notes = _rich_text(slide.notes or "")
    fallback = _label(language, "感谢聆听，欢迎交流讨论。", "Thank you. Questions and discussion are welcome.")
    return f"""
  <section class="slide" data-title="{escape(slide.title)}">
    <p class="kicker">Closing</p>
    <h1 class="h1">{_title_text(slide.title)}</h1>
    <p class="lead mt-m">{takeaway}</p>
    <div class="card mt-l"><p>{_rich_text(slide.notes or fallback)}</p></div>
    {_footer(idx, total)}
    <div class="notes">{notes}</div>
  </section>"""


def _render_slide(
    slide: SlideContent,
    idx: int,
    total: int,
    accent: str,
    layout_name: str,
    figure: Optional[ParsedFigure] = None,
    table: Optional[ParsedTable] = None,
    language: str = "zh",
) -> str:
    if layout_name == "cover":
        return _render_cover(slide, idx, total, language)
    if layout_name == "statement":
        return _render_statement(slide, idx, total, accent)
    if layout_name == "evidence-cards":
        return _render_evidence_cards(slide, idx, total, accent)
    if layout_name == "question-matrix":
        return _render_question_matrix(slide, idx, total, accent, language)
    if layout_name == "method-swimlane":
        return _render_method_swimlane(slide, idx, total, accent, language)
    if layout_name == "critique-panel":
        return _render_critique_panel(slide, idx, total, accent, language)
    if layout_name == "image-left":
        return _render_image_side(slide, idx, total, accent, figure, True)
    if layout_name == "image-right":
        return _render_image_side(slide, idx, total, accent, figure, False)
    if layout_name == "figure-hero":
        return _render_figure_hero(slide, idx, total, accent, figure)
    if layout_name == "figure-method":
        return _render_figure_method(slide, idx, total, accent, figure)
    if layout_name == "figure-results":
        return _render_figure_results(slide, idx, total, accent, figure)
    if layout_name == "figure-compare":
        return _render_figure_compare(slide, idx, total, accent, figure)
    if layout_name in {"section-divider", "cta"}:
        return _render_section_divider(slide, idx, total, accent)
    if layout_name in {"big-quote", "stat-highlight"}:
        return _render_big_quote(slide, idx, total)
    if layout_name == "two-column":
        return _render_columns(slide, idx, total, accent, 2)
    if layout_name in {"three-column", "comparison", "diff", "pros-cons"}:
        return _render_columns(slide, idx, total, accent, 3)
    if layout_name in {"flow-diagram", "arch-diagram", "mindmap", "process-steps", "roadmap", "timeline", "gantt", "toc"}:
        return _render_columns(slide, idx, total, accent, 2)
    if layout_name == "table":
        return _render_table(slide, idx, total, accent, table)
    if layout_name in {"chart-bar", "chart-line", "chart-pie", "chart-radar", "kpi-grid"}:
        return _render_metric_grid(slide, idx, total, accent)
    if layout_name in {"image-grid"}:
        return _render_visual_grid(slide, idx, total, accent, False)
    if layout_name in {"image-hero"}:
        return _render_visual_grid(slide, idx, total, accent, True)
    if layout_name in {"todo-checklist"}:
        return _render_checklist(slide, idx, total, accent)
    if layout_name in {"code", "terminal"}:
        return _render_code(slide, idx, total, accent)
    if layout_name == "thanks":
        return _render_thanks(slide, idx, total, language)
    return _render_bullets(slide, idx, total, accent)


def _figures_section(figures: List[ParsedFigure], idx: int, total: int) -> str:
    cards_html = ""
    for fig in figures[:4]:
        img = ""
        if fig.image_path and Path(fig.image_path).exists():
            rel = Path(fig.image_path).name
            img = (
                f'<img src="figures/{rel}" alt="{escape(fig.caption or fig.figure_id)}" '
                'style="max-width:100%;border-radius:12px"/>'
            )
        cap = escape(fig.caption or fig.figure_id)
        cards_html += f"<div class='card'><h4>{cap}</h4>{img}</div>"
    return f"""
  <section class="slide" data-title="Figures">
    <p class="kicker">Figures</p>
    <h2 class="h2">论文图表</h2>
    <div class="grid g2 mt-l">{cards_html}</div>
    {_footer(idx, total)}
  </section>"""


def _tables_section(tables: List[ParsedTable], idx: int, total: int) -> str:
    rows_html = ""
    for table in tables[:2]:
        if table.image_path and Path(table.image_path).exists():
            rel = Path(table.image_path).name
            rows_html += (
                f"<div class='card'><h4>{escape(table.table_id)}</h4>"
                f'<img src="tables/{rel}" alt="{escape(table.table_id)}" '
                'style="max-width:100%;border-radius:12px"/></div>'
            )
        else:
            body = escape(table.markdown[:1200])
            rows_html += (
                f"<div class='card'><h4>{escape(table.table_id)}</h4>"
                f"<pre class='dim' style='white-space:pre-wrap;font-size:12px'>{body}</pre></div>"
            )
    return f"""
  <section class="slide" data-title="Tables">
    <p class="kicker">Tables</p>
    <h2 class="h2">论文表格</h2>
    <div class="grid g1 mt-l">{rows_html}</div>
    {_footer(idx, total)}
  </section>"""


def build_html_deck(
    task_id: str,
    slides: List[SlideContent],
    template_id: str,
    accent: str,
    figures: Optional[List[ParsedFigure]] = None,
    tables: Optional[List[ParsedTable]] = None,
    layout_names: Optional[List[str]] = None,
    figure_bindings: Optional[Dict[int, int]] = None,
    table_bindings: Optional[Dict[int, int]] = None,
    language: str = "zh",
) -> str:
    output_dir = Path(OUTPUTS_DIR) / task_id / "html"
    output_dir.mkdir(parents=True, exist_ok=True)
    _copy_assets(output_dir)

    figures = figures or []
    tables = tables or []
    layout_names = list(layout_names or [])
    figure_bindings = dict(figure_bindings or {})
    table_bindings = dict(table_bindings or {})
    fig_dir = output_dir / "figures"
    fig_dir.mkdir(exist_ok=True)
    for fig in figures:
        if fig.image_path and Path(fig.image_path).exists():
            dst = fig_dir / Path(fig.image_path).name
            if not dst.exists():
                shutil.copy2(fig.image_path, dst)
    table_dir = output_dir / "tables"
    table_dir.mkdir(exist_ok=True)
    for table in tables:
        if table.image_path and Path(table.image_path).exists():
            dst = table_dir / Path(table.image_path).name
            if not dst.exists():
                shutil.copy2(table.image_path, dst)

    theme = TEMPLATE_THEME_MAP.get(template_id, "minimal-white")
    deck_sections: List[str] = []
    idx = 1
    total = len(slides)

    for slide_index, slide in enumerate(slides):
        layout_name = layout_names[slide_index] if slide_index < len(layout_names) else "bullets"
        figure = None
        figure_idx = figure_bindings.get(slide_index)
        if figure_idx is not None and 0 <= figure_idx < len(figures):
            figure = figures[figure_idx]
        table = None
        table_idx = table_bindings.get(slide_index)
        if table_idx is not None and 0 <= table_idx < len(tables):
            table = tables[table_idx]
        deck_sections.append(_render_slide(slide, idx, total, accent, layout_name, figure, table, language))
        idx += 1
    deck_html = "\n".join(deck_sections)
    doc_lang = "en" if _is_english(language) else "zh-CN"
    html = f"""<!DOCTYPE html>
<html lang="{doc_lang}" data-theme="{theme}">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Paper2PPT Deck</title>
<link rel="stylesheet" href="assets/fonts.css">
<link rel="stylesheet" href="assets/base.css">
<link rel="stylesheet" id="theme-link" href="assets/themes/{theme}.css">
<link rel="stylesheet" href="assets/animations/animations.css">
<style>
.math {{ font-family: "Times New Roman", "STIX Two Math", serif; letter-spacing: .01em; }}
.math-block {{ display: block; margin: 10px 0; padding: 10px 14px; border-radius: 12px; background: rgba(15, 23, 42, .04); }}
.slide {{ padding: 60px 82px; }}
.h2 {{ font-size: 48px; line-height: 1.08; margin-bottom: 10px; }}
.h1 {{ font-size: 66px; }}
.grid {{ gap: 18px; }}
.mt-m {{ margin-top: 14px; }}
.mt-l {{ margin-top: 24px; }}
.card {{ padding: 20px 22px; }}
.slide p, .slide li, .slide td {{ font-size: 19px; line-height: 1.45; }}
.slide li + li {{ margin-top: 6px; }}
.lead, .lede {{ font-size: 23px; line-height: 1.45; }}
</style>
</head>
<body>
<div class="deck">
{deck_html}
</div>
<script src="assets/runtime.js"></script>
</body></html>"""

    index_path = output_dir / "index.html"
    index_path.write_text(html, encoding="utf-8")
    return str(index_path)
